spring.datasource.url=jdbc:postgresql://localhost:5432/telegramBot
spring.datasource.username=Karlitoz_bot
spring.datasource.password=123
telegram.bot.token=8212375777:AAEsXn-zKiLcdvyO6VfXNFHLddVLI3rItBA